name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build Application
        run: |
          ./mvnw clean package

      - name: Deploy to Server
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          scp target/dci-warehouse-final-project.jar $USER@$HOST:/path/to/deploy
          ssh -i $SSH_KEY $USER@$HOST 'sudo systemctl restart dci-warehouse-final-project'
