name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Application
        run: |
          ./mvn clean package -DskipTests
          mv target/dci-warehouse-final-project.jar target/distribution.jar

      - name: DeployStep
        uses: STDSuperman/deploy-files@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          user: ${{ secrets.SERVER_USER }}
          port: '22'
          password: ${{ secrets.SERVER_PASSWORD }}
          targetPath: '/home/test-dir'
          sourcePath: './dist'
          preCommands: |
            rm -rf 1.ts
            rm -rf 2.ts
          commands: |
            touch 1.ts
            touch 2.ts