name: Deploy Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Application
        run: |
          ./mvnw clean package
          mv target/dci-warehouse-final-project.jar target/distribution.jar

      - name: Deploy to Server
        uses: some-action/deploy@v1
        with:
          distribution: ./target/distribution.jar
          api-key: ${{ secrets.API_KEY }}
